# Generated by Django 5.2.3 on 2026-09-26 21:06

import editions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Which email this replaces, e.g. "grants/waitlisted". See the placeholder list below for what you can use in the text.', max_length=100)),
                ('conference_year', models.IntegerField(blank=True, help_text='Leave blank to use this wording for every edition.', null=True, validators=[editions.validators.validate_edition_year])),
                ('subject', models.CharField(help_text='Placeholders work here too, e.g. Accepted: {proposal_title}', max_length=200)),
                ('body', models.TextField(help_text='Plain text. Leave a blank line between paragraphs. Use {placeholder} markers -- anything unrecognised is left alone rather than breaking the email.')),
                ('available_placeholders', models.CharField(blank=True, help_text='For your own reference: which placeholders this email provides.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to fall back to the built-in wording without deleting this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ['key', '-conference_year'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='emails_emai_key_a09a06_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'conference_year'), name='unique_email_template_per_key_per_year')],
            },
        ),
    ]
