# Generated by Django 5.2.3 on 2026-09-27 08:05

import django.db.models.deletion
import editions.current
import editions.validators
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional line shown under the tier heading.', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first. Gold before Silver, and so on.')),
                ('logo_max_width', models.IntegerField(default=200, help_text='Maximum logo width in pixels on the public page. Higher tiers get more room.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this tier and its sponsors from public pages.')),
            ],
            options={
                'verbose_name': 'Sponsor tier',
                'verbose_name_plural': 'Sponsor tiers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_alt', models.CharField(blank=True, help_text="Alt text for the logo. Defaults to the sponsor's name.", max_length=200)),
                ('url', models.URLField(blank=True, help_text='Where the logo links to.')),
                ('conference_year', models.IntegerField(default=editions.current.current_year, help_text='The edition this sponsorship is for.', validators=[editions.validators.validate_edition_year])),
                ('display_order', models.IntegerField(default=0, help_text='Order within the tier.')),
                ('is_published', models.BooleanField(default=False, help_text='Off by default: a sponsor should not appear publicly before the deal is agreed.')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Agreed sponsorship amount.', max_digits=12)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('tickets_allocated', models.IntegerField(default=0, help_text='Complimentary tickets included in this package.')),
                ('tickets_claimed', models.IntegerField(default=0, help_text='How many of those have been taken up.')),
                ('deliverables', wagtail.fields.StreamField([('deliverable', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Logo on the main stage banner', 'max_length': 200}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Tick once delivered.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('item', 0), ('done', 1), ('note', 2)]], {'icon': 'tick', 'label': 'Deliverable'})}, help_text='What was promised, and whether it has been delivered.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tier', models.ForeignKey(help_text='Protected: a tier with sponsors attached cannot be deleted by accident.', on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.sponsortier')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['tier__display_order', 'display_order', 'name'],
                'indexes': [models.Index(fields=['conference_year', 'is_published'], name='sponsors_sp_confere_a922bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'conference_year'), name='unique_sponsor_per_edition')],
            },
        ),
    ]
