# Generated by Django 5.2.3 on 2026-09-29 08:36

import django.db.models.deletion
import editions.validators
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(unique=True, validators=[editions.validators.validate_edition_year])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Applications close after this. Blank means they stay open while the status is Open.', null=True)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='What volunteering at PyCon Nigeria involves.')),
                ('what_we_ask', wagtail.fields.RichTextField(blank=True, help_text='The commitment, stated plainly: how many shifts, which days, whether training is required. People decline for good reasons, and finding out late costs everybody more.')),
                ('what_you_get', wagtail.fields.RichTextField(blank=True, help_text='A ticket, a shirt, food on shift, a certificate. Say it explicitly.')),
                ('target_count', models.IntegerField(default=0, help_text='How many volunteers this edition needs in total. 0 means no target set.')),
                ('setup_days_before', models.IntegerField(default=1, help_text='Days before the conference that need volunteers, for set-up. Adds those days to the availability question on the form.')),
                ('teardown_days_after', models.IntegerField(default=1, help_text='Days after the conference that need volunteers, for pack-down.')),
                ('max_team_choices', models.IntegerField(default=3, help_text='How many teams an applicant may put themselves forward for.')),
                ('shifts_published', models.BooleanField(default=False, help_text='Until this is on, volunteers cannot see their shifts. Rosters get rebuilt several times before they settle, and a volunteer who reads a draft roster turns up at the wrong hour.')),
                ('certificates_available_from', models.DateTimeField(blank=True, help_text='Certificates appear for volunteers who worked a shift after this moment. Blank means never -- normally set to the day after the conference.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'volunteer settings',
                'verbose_name_plural': 'volunteer settings',
                'ordering': ['-conference_year'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Registration, Room hosts, AV', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('conference_year', models.IntegerField(validators=[editions.validators.validate_edition_year])),
                ('description', models.TextField(blank=True, help_text="What this team actually does, in the applicant's words.")),
                ('target_count', models.IntegerField(default=0, help_text='How many volunteers this team needs. 0 means no target.')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive teams keep their history but are not offered on the form.')),
                ('lead', models.ForeignKey(blank=True, help_text='The named person a volunteer on this team reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_teams_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('slug', 'conference_year')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_year', models.IntegerField(validators=[editions.validators.validate_edition_year])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not selected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('full_name', models.CharField(help_text='As they want it on a badge.', max_length=150)),
                ('phone', models.CharField(blank=True, help_text='For the day itself. A team lead with twelve people needs to reach them.', max_length=40)),
                ('experience', models.CharField(choices=[('none', 'This would be my first time'), ('some', 'I have volunteered at an event before'), ('lots', 'I have run or coordinated events')], default='none', max_length=20)),
                ('experience_detail', models.TextField(blank=True, help_text='Anything they want to add about it.')),
                ('motivation', models.TextField(help_text='Why they want to help. Read before any decision is made.')),
                ('skills', models.CharField(blank=True, help_text='Languages spoken, first aid, AV, photography, sign language -- whatever would change which team they are put on.', max_length=300)),
                ('tshirt_size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', '2XL'), ('xxxl', '3XL')], max_length=8)),
                ('dietary_requirements', models.CharField(blank=True, help_text='Anything the caterers need to know.', max_length=255)),
                ('accessibility_needs', models.TextField(blank=True, help_text='What they need to work comfortably. Read it before assigning a shift, not after.')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40)),
                ('decision_note', models.TextField(blank=True, help_text='Shown to the applicant with the decision. A rejection with a sentence is a person you can ask again next year.')),
                ('internal_note', models.TextField(blank=True, help_text='Never shown to the applicant.')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lead', models.ForeignKey(blank=True, help_text="Defaults to the team's lead, but can differ for a large team.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers_led', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_decisions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_volunteers', to='volunteers.volunteerteam')),
                ('teams', models.ManyToManyField(help_text='Teams they would be happy to work in.', related_name='interested_applications', to='volunteers.volunteerteam')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(validators=[editions.validators.validate_edition_year])),
                ('title', models.CharField(help_text='e.g. Registration desk, Saturday morning', max_length=150)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='Where to physically stand.', max_length=200)),
                ('capacity', models.IntegerField(default=1, help_text='How many volunteers this shift needs.')),
                ('notes', models.TextField(blank=True, help_text='Shown to the volunteers on this shift.')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteers.volunteerteam')),
            ],
            options={
                'ordering': ['starts_at', 'team__display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField(blank=True, help_text='Set when the volunteer actually worked the shift.', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteers.shift')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='volunteers.volunteerapplication')),
            ],
            options={
                'ordering': ['shift__starts_at'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'application'), name='one_assignment_per_shift')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='volunteers.volunteerapplication')),
            ],
            options={
                'ordering': ['day', 'period'],
                'constraints': [models.UniqueConstraint(fields=('application', 'day', 'period'), name='one_availability_slot')],
            },
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['conference_year', 'status'], name='volunteers__confere_19b8b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.UniqueConstraint(fields=('user', 'conference_year'), name='one_volunteer_application_per_user_per_year'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['conference_year', 'starts_at'], name='volunteers__confere_899104_idx'),
        ),
    ]
