# Generated by Django 5.2.3 on 2026-09-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='How the actor was identified at the time -- an email address, or "system". Kept as written so the trail survives the account being renamed or deleted.', max_length=200)),
                ('action', models.CharField(help_text='Short description, e.g. "Approved grant" or "Rejected proposal".', max_length=120)),
                ('old_value', models.CharField(blank=True, max_length=120)),
                ('new_value', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('target_id', models.CharField(blank=True, help_text='Primary key as text, because targets use integer and UUID keys.', max_length=64)),
                ('target_label', models.CharField(blank=True, help_text='How the target read at the time, so the trail stays legible if it is deleted.', max_length=255)),
                ('conference_year', models.IntegerField(blank=True, help_text='Edition this action belongs to, where the target has one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The account that acted. Null for automated actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit entry',
                'verbose_name_plural': 'Audit trail',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__55fc83_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_b1db01_idx'), models.Index(fields=['conference_year'], name='audit_audit_confere_270ea6_idx')],
            },
        ),
    ]
