# Generated by Django 5.2.3 on 2026-09-26 20:32

import django.db.models.deletion
import editions.current
import editions.validators
import meetups.models
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfp', '0005_alter_cfpsettings_conference_year_and_more'),
        ('tickets', '0002_alter_coupon_conference_year_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Shown above the meetup list.')),
                ('show_newsletter_signup', models.BooleanField(default=True, help_text='Show the mailing-list form on this page and its chapter pages.')),
                ('newsletter_heading', models.CharField(blank=True, default='Get early-bird access', help_text='Heading above the mailing-list form.', max_length=150)),
                ('newsletter_blurb', models.CharField(blank=True, default='Join the mailing list for conference announcements and early-bird tickets.', max_length=255)),
            ],
            options={
                'verbose_name': 'Meetup Index Page',
            },
            bases=(meetups.models.ThemedPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='CityChapterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('city', models.CharField(help_text='City name, e.g. Lagos. Used in listings.', max_length=100)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('hero_image_alt', models.CharField(blank=True, help_text='Describe the image for screen readers.', max_length=200)),
                ('meetup_com_url', models.URLField(blank=True, help_text="The chapter's Meetup.com group page.")),
                ('organizers', wagtail.fields.StreamField([('organizer', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Lead organizer', 'max_length': 120, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the photo for screen readers.', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Their site, LinkedIn or GitHub', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('photo', 2), ('photo_alt', 3), ('link', 4)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'City Chapter Page',
            },
            bases=(meetups.models.ThemedPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Lagos Python Meetup - October"', max_length=200)),
                ('starts_at', models.DateTimeField(help_text='Local date and time it starts.')),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True, help_text='A couple of lines for the listing.')),
                ('meetup_url', models.URLField(help_text='The Meetup.com event page where people RSVP.')),
                ('conference_year', models.IntegerField(default=editions.current.current_year, help_text='The edition this meetup leads up to.', validators=[editions.validators.validate_edition_year])),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the public listing while preparing it.')),
                ('recap', wagtail.fields.StreamField([('paragraph', 0), ('photo', 4), ('embed', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the photo for screen readers.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt', 2), ('caption', 3)]], {'icon': 'image', 'label': 'Photo'}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or other recording URL', 'label': 'Recording link'})}, help_text='Photos, notes and recording links, added after the meetup.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee_coupon', models.ForeignKey(blank=True, help_text="Optional discount code to offer this meetup's attendees.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetups', to='tickets.coupon')),
                ('chapter', models.ForeignKey(help_text='Which city chapter is holding this.', on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='meetups.citychapterpage')),
            ],
            options={
                'verbose_name': 'Meetup',
                'verbose_name_plural': 'Meetups',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetupTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('speaker_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True, help_text='Used to pre-fill a conference proposal if this talk is promoted.')),
                ('slides_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('meetup', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='meetups.meetup')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetup_talks_promoted', to=settings.AUTH_USER_MODEL)),
                ('promoted_proposal', models.ForeignKey(blank=True, help_text='The conference proposal created from this talk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_meetup_talks', to='cfp.proposal')),
                ('user', models.ForeignKey(blank=True, help_text='Link to their account if they have one. Required to promote this into the CFP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetup_talks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meetup talk',
                'verbose_name_plural': 'Meetup talks',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['starts_at'], name='meetups_mee_starts__4c02d6_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['conference_year', 'is_published'], name='meetups_mee_confere_ccfe36_idx'),
        ),
    ]
