# Generated by Django 5.2.3 on 2026-09-26 19:58

import editions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='conference_year',
            field=models.IntegerField(help_text='Conference year this coupon is valid for', validators=[editions.validators.validate_edition_year]),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='conference_year',
            field=models.IntegerField(help_text='Conference year this ticket type belongs to', validators=[editions.validators.validate_edition_year]),
        ),
    ]
