# Generated by Django 5.2.3 on 2026-09-27 18:19

import django.db.models.deletion
import editions.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        ('tickets', '0002_alter_coupon_conference_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='Sequential within the edition, e.g. PYNG-2027-0001.', max_length=40, unique=True)),
                ('conference_year', models.IntegerField(validators=[editions.validators.validate_edition_year])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, help_text='Empty for an individual buyer, in which case the name above stands alone.', max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('buyer_tax_id', models.CharField(blank=True, help_text="The buyer's own tax number, where their finance team needs it shown.", max_length=60)),
                ('purchase_order_reference', models.CharField(blank=True, help_text='Their PO number, if they gave one. Often the only way they can pay.', max_length=100)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='What is being paid back. May be less than what was paid.', max_digits=10)),
                ('reason', models.TextField(help_text="The requester's words.")),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved, not yet paid'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('paid_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('provider_reference', models.CharField(blank=True, help_text="Paystack's refund reference, or the bank transfer reference.", max_length=120)),
                ('note', models.TextField(blank=True, help_text="The organizer's note. Internal.")),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(unique=True, validators=[editions.validators.validate_edition_year])),
                ('transfer_deadline', models.DateTimeField(blank=True, help_text='Last moment a ticket can be passed to someone else. Badges are printed from attendee names, so this normally sits a few days before the event. Blank means transfers stay open.', null=True)),
                ('refund_deadline', models.DateTimeField(blank=True, help_text='Last moment a refund can be requested. Blank means no refunds are offered, which is also a policy -- say so in the text below.', null=True)),
                ('refund_policy', models.TextField(blank=True, help_text='Shown on the purchase page and the ticket page. Write what you will actually do, including any fee retained.')),
                ('refund_fee_percentage', models.IntegerField(default=0, help_text='Percentage retained on a refund, for the amount suggested to the organizer.')),
                ('waitlist_enabled', models.BooleanField(default=True, help_text='Offer a waitlist when a ticket type sells out.')),
                ('checkin_opens_at', models.DateTimeField(blank=True, help_text='Before this, a check-in scan is refused. Blank means any time.', null=True)),
                ('invoice_prefix', models.CharField(default='PYNG', help_text='Prefix for invoice numbers, e.g. PYNG gives PYNG-2027-0001.', max_length=12)),
                ('invoice_from_name', models.CharField(blank=True, help_text='The legal name that appears as the seller on an invoice.', max_length=200)),
                ('invoice_from_address', models.TextField(blank=True)),
                ('invoice_tax_id', models.CharField(blank=True, help_text='Your tax identification number, if invoices need to carry one.', max_length=60)),
                ('invoice_notes', models.TextField(blank=True, help_text='Standing footnote on every invoice, e.g. how to reference a payment.')),
            ],
            options={
                'verbose_name': 'ticket settings',
                'verbose_name_plural': 'ticket settings',
                'ordering': ['-conference_year'],
            },
        ),
        migrations.CreateModel(
            name='TicketWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(validators=[editions.validators.validate_edition_year])),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Set when they were told a place opened up. Stops a second telling.', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='Set when they went on to buy.', null=True)),
            ],
            options={
                'verbose_name': 'waitlist entry',
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketsale',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used when the type is a fixed amount. Never takes a total below zero.', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, help_text='What this code is for, so a stray code can be recognised later.', max_length=200),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_per_user',
            field=models.IntegerField(default=0, help_text='Times one person may use it. 0 means no per-person limit.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to every ticket type.', related_name='coupons', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Blank means valid immediately.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Blank means no expiry date. Set this rather than relying on somebody remembering to tick the box below.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='complimentary_reason',
            field=models.CharField(blank=True, help_text='Why this ticket was issued without payment: speaker, volunteer, grant recipient, sponsor allocation. Empty on a purchased ticket.', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What the coupon took off, recorded when it was applied. Not recomputed from the coupon, whose terms may have changed since.', max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Who issued a complimentary ticket, or empty when a command did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issued_for_sponsor',
            field=models.ForeignKey(blank=True, help_text="Set when this came out of a sponsor's ticket allocation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to='sponsors.sponsor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verification_note',
            field=models.CharField(blank=True, help_text="The reviewer's note. Internal.", max_length=300),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verification_reference',
            field=models.CharField(blank=True, help_text='What the buyer supplied, in their words. Never validated automatically.', max_length=300),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verification_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='attendee_email',
            field=models.EmailField(blank=True, help_text='Who this place is for. Kept even after the account is linked, so the order still shows who the buyer named.', max_length=254),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='checkin_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='What the QR code carries, and what a volunteer can type instead.', max_length=16),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='When this place last changed hands.', null=True),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='transferred_from_email',
            field=models.EmailField(blank=True, help_text='Who held it before the last transfer, so a chain stays traceable.', max_length=254),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='availability',
            field=models.CharField(choices=[('public', 'On sale to the public'), ('invite', 'Issued only, never shown for sale')], default='public', help_text="Issued-only types never appear on the purchase page. Use one for a sponsor's allocation, or for speaker and volunteer tickets.", max_length=20),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='early_bird_ends_at',
            field=models.DateTimeField(blank=True, help_text='Early bird also ends at this moment, whether or not the allocation has run out. Blank means the count alone decides.', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_per_order',
            field=models.IntegerField(default=10, help_text='Most of this type one person may buy at once. Keeps a mistyped quantity from consuming the whole allocation.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='requires_verification',
            field=models.BooleanField(default=False, help_text='Ask the buyer for something to check, and flag the order for review. Use for a student or concession rate.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sales_end_at',
            field=models.DateTimeField(blank=True, help_text='Sales close at this moment. Blank means no end.', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sales_start_at',
            field=models.DateTimeField(blank=True, help_text='Sales open at this moment. Blank means already open.', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='verification_prompt',
            field=models.CharField(blank=True, help_text="What to ask for, e.g. 'Your institution and student ID number'. Shown only when verification is required.", max_length=200),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expired',
            field=models.BooleanField(default=False, help_text='A manual kill switch, independent of the dates above.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.IntegerField(default=5, help_text='Used when the type is a percentage. 5 means 5% off.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Issued'), (2, 'Paid'), (3, 'Refunded'), (4, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='user',
            field=models.ForeignKey(blank=True, help_text="The attendee's own account. Empty until they have one -- a place can be assigned by email before its owner has signed up.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['conference_year', 'status'], name='tickets_tic_confere_bb1c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['verification_status'], name='tickets_tic_verific_46fc4b_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='refund',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketwaitlistentry',
            name='ticket_type',
            field=models.ForeignKey(blank=True, help_text='Empty means any ticket type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='ticketwaitlistentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='tickets_ref_status_61574f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketwaitlistentry',
            constraint=models.UniqueConstraint(fields=('conference_year', 'ticket_type', 'email'), name='unique_waitlist_entry_per_type'),
        ),
    ]
