# Generated by Django 5.2.3 on 2026-09-27 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_checkin_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticketwaitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_type__isnull', True)), fields=('conference_year', 'email'), name='unique_waitlist_entry_any_type'),
        ),
    ]
