# Generated by Django 5.2.3 on 2026-09-26 19:58

import editions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_nav_page_chooser_and_login_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='conference_year',
            field=models.IntegerField(blank=True, help_text='The conference year this page represents (e.g., 2024, 2025). Leave blank for current year.', null=True, validators=[editions.validators.validate_edition_year]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='theme',
            field=models.CharField(blank=True, default='', help_text="Template theme override, e.g. theme_2026. Leave blank to use the theme set on this page's Edition.", max_length=50),
        ),
    ]
