# Generated by Django 5.2.3 on 2026-09-27 08:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_conference_year_alter_homepage_theme'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='sponsorpage',
            name='current_sponsors_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsorpage',
            name='current_sponsors_title',
            field=models.CharField(default='Our sponsors', help_text='Heading above the sponsor logos.', max_length=200),
        ),
        migrations.AddField(
            model_name='sponsorpage',
            name='prospectus',
            field=models.ForeignKey(blank=True, help_text='The sponsorship prospectus, usually a PDF. Upload it under Documents and choose it here; replacing the file needs no deploy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='sponsorpage',
            name='prospectus_label',
            field=models.CharField(blank=True, default='Download the prospectus', help_text='Text on the download button.', max_length=80),
        ),
        migrations.AddField(
            model_name='sponsorpage',
            name='prospectus_note',
            field=models.CharField(blank=True, help_text='Optional line under the button, e.g. "PDF, 2.4 MB".', max_length=200),
        ),
        migrations.AddField(
            model_name='sponsorpage',
            name='show_current_sponsors',
            field=models.BooleanField(default=True, help_text="Show this edition's published sponsors, grouped by tier."),
        ),
    ]
