# Generated by Django 5.2.3 on 2026-09-27 08:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepage_sponsors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='countdown_label',
            field=models.CharField(blank=True, default='until the conference', help_text='Text under the countdown.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phase_ctas',
            field=wagtail.fields.StreamField([('cta', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [], 'help_text': 'Which phase this wording applies to.'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Path or full URL. Relative paths like /tickets/ are fine.', 'max_length': 500}), 3: ('wagtail.blocks.StructBlock', [[('phase', 0), ('label', 1), ('url', 2)]], {})}, help_text='Optional: reword the primary button for particular phases. Without an entry, sensible defaults are used. The hero button fields above override this entirely if you fill them in.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_countdown',
            field=models.BooleanField(default=True, help_text='Show a countdown to the first day. Needs a start date on the Edition.'),
        ),
    ]
