# Generated by Django 5.2.3 on 2026-09-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_countdown_label_homepage_phase_ctas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Register Now', help_text='Overrides the automatic button. Clear this (and the URL) to let the button follow the conference phase instead.', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Call for Papers', help_text='Secondary button text. Leave blank to hide the button.', max_length=50),
        ),
    ]
