# Generated by Django 5.2.3 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The edition year, e.g. 2027. Used to scope every record.', unique=True)),
                ('name', models.CharField(help_text='Theme name shown on the site, e.g. "Future Forward".', max_length=100)),
                ('description', models.CharField(blank=True, help_text="One line describing this edition's design or focus.", max_length=255)),
                ('theme', models.SlugField(help_text='Theme slug. Selects the stylesheet (static/css/<theme>.css), the theme script and the base template. Free text, so a new theme needs no migration.')),
                ('primary_color', models.CharField(default='#14b8a6', help_text='Hex, e.g. #14b8a6. Used for theme-color.', max_length=7)),
                ('secondary_color', models.CharField(default='#3b82f6', help_text='Hex.', max_length=7)),
                ('accent_color', models.CharField(default='#f97316', help_text='Hex.', max_length=7)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=False, help_text='The edition the site presents at its root URL. Exactly one edition is current; ticking this unticks the others.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to keep an edition out of the year navigation while preparing it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'ordering': ['-year'],
            },
        ),
    ]
