# Generated by Django 5.2.3 on 2026-09-27 13:39

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('response_time', models.CharField(blank=True, help_text="What to expect, e.g. 'We usually reply within two working days.' Saying nothing is better than promising something you will not meet.", max_length=200)),
                ('contact_methods', wagtail.fields.StreamField([('method', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The address, number or handle itself.', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link. Use mailto: or tel: to make it one tap on a phone.', 'max_length': 300, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'What this route is for, so people pick the right one.', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('detail', 1), ('url', 2), ('note', 3)]], {'icon': 'mail', 'label': 'Contact method'})})),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Shown after the form is sent.')),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A sentence or two above the questions.')),
                ('no_answer_heading', models.CharField(default='Still stuck?', help_text='Heading for the fallback at the foot of the page.', max_length=200)),
                ('no_answer_text', wagtail.fields.RichTextField(blank=True, help_text='Where to go if their question is not here. Link the contact page.')),
            ],
            options={
                'verbose_name': 'FAQ page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TravelPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('callout', 7), ('venue', 14), ('places_to_stay', 20), ('getting_here', 23), ('questions', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'What the image shows, for someone who cannot see it. Leave blank only if it is purely decorative.', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 1)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'As you would write it on an envelope, or read it to a driver.'}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'A link to the venue on a map. A link rather than an embedded map: an embed is a third-party script on every page load, and it is the one thing that will not work on a slow connection.', 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Landmarks, entrances, which gate to use.', 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Step-free access, lifts, accessible toilets, quiet spaces. Say what is there and what is not -- a gap somebody discovers on the day is worse than a gap they could plan around.', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt', 3), ('caption', 4)]], {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('name', 8), ('address', 9), ('map_url', 10), ('directions', 11), ('accessibility', 12), ('image', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "From the venue, as people think of it: '10 minutes on foot'.", 'max_length': 100, 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'A range in naira per night. A band, not a quote -- it will change.', 'max_length': 100, 'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('name', 8), ('distance', 15), ('price_band', 16), ('url', 17), ('notes', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'help_text': 'Rendered as a comparable list. Order them as you would recommend them.', 'label': 'Places to stay'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'By air, by road, by ride-hailing, on foot.', 'max_length': 100}), 22: ('wagtail.blocks.StructBlock', [[('mode', 21), ('detail', 1)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Getting here'}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 25: ('wagtail.blocks.StructBlock', [[('question', 24), ('answer', 1)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'help_text': 'Visas, currency, insurance -- whatever gets asked most.', 'label': 'Travel questions'})})),
            ],
            options={
                'verbose_name': 'Travel and venue page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='info.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section', models.CharField(blank=True, help_text="Groups this question with others, e.g. 'Tickets' or 'Travel'. Leave blank for 'General'.", max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('answer', wagtail.fields.RichTextField()),
                ('anchor', models.SlugField(blank=True, help_text='Optional. Makes this question linkable as #your-anchor, so support replies can point straight at the answer.', max_length=80)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='info.faqpage')),
            ],
            options={
                'verbose_name': 'question',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
