# Generated by Django 5.2.3 on 2026-09-27 08:58

import django.db.models.deletion
import editions.current
import editions.validators
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfp', '0007_delete_emailtemplate'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(default=editions.current.current_year, validators=[editions.validators.validate_edition_year])),
                ('alt', models.CharField(help_text='Describe the photo for screen readers. Required.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Edition photo',
                'verbose_name_plural': 'Edition photos',
                'ordering': ['-conference_year', 'display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='YearArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('conference_year', models.IntegerField(help_text='Which past edition this page archives.', validators=[editions.validators.validate_edition_year])),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A short look back. Shown above the talks.')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200)),
                ('talks_title', models.CharField(default='Talks', max_length=200)),
                ('photos_title', models.CharField(default='Photos', max_length=200)),
                ('show_talks', models.BooleanField(default=True)),
                ('show_photos', models.BooleanField(default=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Year Archive Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(default=editions.current.current_year, help_text='The edition this talk belongs to.', validators=[editions.validators.validate_edition_year])),
                ('title', models.CharField(max_length=250)),
                ('abstract', models.TextField(blank=True, help_text='What the talk was about. Shown on the archive listing.')),
                ('speaker_names', models.CharField(blank=True, help_text='Speaker names as they should read, comma separated. Use this for past editions whose speakers have no account here.', max_length=300)),
                ('track_name', models.CharField(blank=True, max_length=120)),
                ('duration', models.IntegerField(blank=True, help_text='Minutes.', null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other recording.')),
                ('slides_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True, help_text='Code or materials.')),
                ('room', models.CharField(blank=True, help_text='Left for the schedule builder. Not used by the archive.', max_length=120)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Left for the schedule builder. Not used by the archive.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(blank=True, help_text='The proposal this came from, when it went through the CFP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='cfp.proposal')),
                ('speakers', models.ManyToManyField(blank=True, help_text="Link accounts where they exist, so a speaker's talks can be listed together.", related_name='talks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talk',
                'verbose_name_plural': 'Talks',
                'ordering': ['-conference_year', 'display_order', 'title'],
                'indexes': [models.Index(fields=['conference_year', 'is_published'], name='program_tal_confere_fb7219_idx')],
            },
        ),
    ]
