# Generated by Django 5.2.3 on 2026-09-27 09:20

import django.db.models.deletion
import editions.current
import editions.validators
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('conference_year', models.IntegerField(blank=True, help_text='Leave blank to follow the edition of the page above this one.', null=True, validators=[editions.validators.validate_edition_year])),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('empty_message', models.CharField(default='The schedule is not published yet. Check back soon.', help_text='Shown when nothing has been scheduled.', max_length=255)),
                ('allow_saving', models.BooleanField(default=True, help_text='Let signed-in visitors build a personal schedule.')),
            ],
            options={
                'verbose_name': 'Schedule Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpeakersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('conference_year', models.IntegerField(blank=True, help_text='Leave blank to follow the edition of the page above this one.', null=True, validators=[editions.validators.validate_edition_year])),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('empty_message', models.CharField(default='Speakers will be announced once talks are selected.', max_length=255)),
            ],
            options={
                'verbose_name': 'Speakers Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='talk',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='When it starts. Empty means not yet scheduled.', null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('conference_year', models.IntegerField(default=editions.current.current_year, validators=[editions.validators.validate_edition_year])),
                ('capacity', models.IntegerField(blank=True, help_text='Seats. Used to cap workshop sign-ups later.', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Left-to-right order in the schedule grid.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['conference_year', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'conference_year'), name='unique_room_slug_per_edition')],
            },
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Leave empty for an archived talk, or one not yet scheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='program.room'),
        ),
        migrations.CreateModel(
            name='SavedTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='program.talk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_talks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved talk',
                'verbose_name_plural': 'Saved talks',
                'ordering': ['talk__starts_at', 'talk__title'],
                'indexes': [models.Index(fields=['user'], name='program_sav_user_id_39f019_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'talk'), name='unique_saved_talk_per_user')],
            },
        ),
    ]
