# Generated by Django 5.2.3 on 2026-09-26 19:58

import editions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_alter_grantreviewerassignment_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantsettings',
            name='conference_year',
            field=models.IntegerField(unique=True, validators=[editions.validators.validate_edition_year]),
        ),
    ]
