# Generated by Django 5.2.3 on 2026-09-29 10:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_alter_grantsettings_conference_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelgrantpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='grantsettings',
            name='acceptance_days',
            field=models.IntegerField(default=14, help_text='How many days a recipient has to accept an offer before it lapses. An offer nobody answers holds budget that could go to the next person on the waitlist. 0 means offers never lapse.'),
        ),
        migrations.AddField(
            model_name='grantsettings',
            name='auto_promote_waitlist',
            field=models.BooleanField(default=True, help_text='When a grant is declined or lapses, offer the freed money to the highest-scoring waitlisted applicant it covers.'),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='acceptance_deadline',
            field=models.DateTimeField(blank=True, help_text="Set when the grant is approved, from the edition's acceptance window. After this the offer lapses and its money returns to the budget.", null=True),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='account_name',
            field=models.CharField(blank=True, help_text='Exactly as the bank holds it, or the transfer bounces.', max_length=150),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='decision_note',
            field=models.TextField(blank=True, help_text='Shown to the applicant with the decision.'),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='decline_reason',
            field=models.TextField(blank=True, help_text="Why they turned it down, in their words. Worth reading: 'the amount would not cover the flight' is a different problem from 'I can no longer come'."),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('self_describe', 'Prefer to self-describe'), ('undisclosed', 'Prefer not to say')], default='', help_text='Optional. Collected only because sponsor and PSF reports ask for the breakdown; never shown to reviewers and never a factor in a decision.', max_length=20),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='gender_self_described',
            field=models.CharField(blank=True, help_text='Used when they chose to self-describe.', max_length=100),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='grant_type',
            field=models.CharField(choices=[('travel', 'Travel only'), ('accommodation', 'Accommodation only'), ('both', 'Travel and accommodation')], default='both', help_text='What they are asking for. Asked explicitly rather than inferred from which cost fields happen to be filled in, so the review queue can be filtered by it and the reports can report on it.', max_length=20),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='is_speaking',
            field=models.BooleanField(default=False, help_text='Declared by the applicant. Stored rather than derived from the CFP at read time, so the answer they gave survives a proposal being withdrawn and a reviewer sees what was said when it was said.'),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('other', 'Something else (tell us below)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='payout_notes',
            field=models.TextField(blank=True, help_text='Anything finance needs to know to pay them.'),
        ),
        migrations.AddField(
            model_name='travelgrantapplication',
            name='promoted_from_waitlist_at',
            field=models.DateTimeField(blank=True, help_text='Set when this application was moved off the waitlist into an offer.', null=True),
        ),
        migrations.AddField(
            model_name='travelgrantpayment',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='travelgrantpayment',
            name='receipt_verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='travelgrantpayment',
            name='receipt_verified_by',
            field=models.ForeignKey(blank=True, help_text='Who checked the receipt against the amount paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_receipts_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grantsettings',
            name='max_per_applicant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum grant amount per applicant. Enforced when a decision is made, not merely displayed. 0 means no per-applicant limit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelgrantapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved, awaiting acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined by applicant'), ('lapsed', 'Lapsed, not accepted in time'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not Selected'), ('withdrawn', 'Withdrawn'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelgrantpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('verified', 'Receipt verified')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelgrantpayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Uploaded by the recipient or by finance. A reimbursement needs one before it can be verified.', null=True, upload_to='grant_receipts/%Y/'),
        ),
    ]
