# Generated by Django 5.2.3 on 2026-09-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_alter_cfpsettings_guidelines_alter_proposal_abstract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfp_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReviewerProfile',
        ),
    ]
