# Generated by Django 5.2.3 on 2026-09-26 19:58

import editions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0004_speaker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfpsettings',
            name='conference_year',
            field=models.IntegerField(unique=True, validators=[editions.validators.validate_edition_year]),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='conference_year',
            field=models.IntegerField(validators=[editions.validators.validate_edition_year]),
        ),
        migrations.AlterField(
            model_name='track',
            name='conference_year',
            field=models.IntegerField(validators=[editions.validators.validate_edition_year]),
        ),
    ]
