# Generated by Django 5.2.3 on 2026-09-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0005_alter_cfpsettings_conference_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalAuditLog',
        ),
    ]
