# Generated by Django 5.2.3 on 2026-09-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0006_delete_proposalauditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
