# Generated by Django 5.2.3 on 2026-09-27 13:26

import django.db.models.deletion
import editions.validators
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOfConductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A short statement of intent, shown under the title.')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('expectations', 3), ('unacceptable', 4), ('callout', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'One expectation per line.', 'label': 'Expected behaviour'}), 4: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'One item per line.', 'label': 'Unacceptable behaviour'}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 1)]], {'label': 'Callout'})})),
                ('show_report_form', models.BooleanField(default=True, help_text='Offer the reporting form from this page. Turning this off hides the link but does not close the form at /conduct/report/.')),
                ('report_heading', models.CharField(default='Reporting a breach', help_text='Heading above the reporting call to action.', max_length=200)),
                ('report_intro', wagtail.fields.RichTextField(blank=True, help_text='What to expect if they report. Say who reads it and how soon.')),
                ('response_promise', models.CharField(blank=True, help_text="The commitment shown beside the form, e.g. 'A member of the Code of Conduct team will respond within 24 hours.' Leave blank to say nothing.", max_length=300)),
                ('emergency_contacts', wagtail.fields.StreamField([('contact', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "How they are introduced, e.g. 'Code of Conduct lead'.", 'max_length': 120, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown as a tel: link, so it is one tap on a phone.', 'max_length': 40, 'required': False}), 3: ('wagtail.blocks.EmailBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('phone', 2), ('email', 3)]], {})}, help_text='People to reach during the event. Editable here so a phone number can be corrected on the day without a deploy.')),
            ],
            options={
                'verbose_name': 'Code of Conduct page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, help_text='Quoted by the reporter and by the team. Generated, never typed.', max_length=32, unique=True)),
                ('conference_year', models.IntegerField(help_text='Which edition this report belongs to.', validators=[editions.validators.validate_edition_year])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Set by the reporter. When true, no name or email was collected.')),
                ('reporter_name', models.CharField(blank=True, max_length=200)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('incident_when', models.CharField(blank=True, help_text="In the reporter's words, e.g. 'Saturday, during the lightning talks'.", max_length=200)),
                ('incident_where', models.CharField(blank=True, help_text='Room, venue, or the online channel.', max_length=200)),
                ('people_involved', models.TextField(blank=True, help_text='Names or descriptions, as given. May be empty.')),
                ('description', models.TextField(help_text="What happened, in the reporter's words.")),
                ('witnesses', models.TextField(blank=True)),
                ('desired_outcome', models.TextField(blank=True, help_text='What the reporter asked for. Read this before deciding anything.')),
                ('reported_elsewhere', models.BooleanField(default=False, help_text='The reporter says they have also told someone else, on-site or off.')),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('no_action', 'Closed, no action')], default='new', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='What was decided and done. Internal.')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduct_reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reporter_user', models.ForeignKey(blank=True, help_text='Recorded only when the reporter was signed in and did not ask to be anonymous. An anonymous report is never linked to an account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduct_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code of Conduct report',
                'verbose_name_plural': 'Code of Conduct reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('author_label', models.CharField(blank=True, help_text='Kept as written, so the note stays legible after an account is renamed.', max_length=200)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='conduct.incidentreport')),
            ],
            options={
                'verbose_name': 'note',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['conference_year', 'status'], name='conduct_inc_confere_9525bd_idx'),
        ),
    ]
