# Generated by Django 5.2.3 on 2026-09-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cfp_reviewer', 'CFP reviewer'), ('cfp_chair', 'CFP chair'), ('grant_reviewer', 'Grant reviewer'), ('grant_chair', 'Grant chair'), ('finance', 'Finance'), ('volunteer', 'Volunteer'), ('sponsor_contact', 'Sponsor contact'), ('organizer', 'Organizer')], max_length=32)),
                ('conference_year', models.IntegerField(blank=True, help_text='Edition this role applies to. Leave blank for every edition.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to revoke without losing the record of who granted it.')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Why this role was granted, for whoever reads this later.')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Who conferred this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role assignment',
                'verbose_name_plural': 'Role assignments',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_ro_user_id_c02541_idx'), models.Index(fields=['role', 'conference_year'], name='accounts_ro_role_e7c77f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'conference_year'), name='unique_role_per_user_per_year')],
            },
        ),
    ]
