# Generated by Django 5.2.3 on 2026-09-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_roleassignment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('cfp_reviewer', 'CFP reviewer'), ('cfp_chair', 'CFP chair'), ('grant_reviewer', 'Grant reviewer'), ('grant_chair', 'Grant chair'), ('finance', 'Finance'), ('volunteer', 'Volunteer'), ('sponsor_contact', 'Sponsor contact'), ('organizer', 'Organizer'), ('coc_team', 'Code of Conduct team'), ('volunteer_chair', 'Volunteer coordinator')], max_length=32),
        ),
    ]
