# Generated by Django 5.2.3 on 2026-09-27 13:41

import django.db.models.deletion
import django.utils.timezone
import editions.current
import editions.validators
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('empty_text', models.CharField(default='Nothing here yet. Announcements will appear on this page.', help_text='Shown when there are no posts, so the page is never blank.', max_length=300)),
            ],
            options={
                'verbose_name': 'Blog index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('published_on', models.DateField(default=django.utils.timezone.localdate, help_text="The date shown to readers. Separate from Wagtail's own publish time so a post written in advance carries the date it is about.")),
                ('conference_year', models.IntegerField(default=editions.current.current_year, help_text='Which edition this post belongs to.', validators=[editions.validators.validate_edition_year])),
                ('byline', models.CharField(blank=True, help_text='Who wrote it, as you want it to read. Free text rather than an account, because posts are often written by a team or by somebody without one.', max_length=200)),
                ('summary', models.CharField(help_text='One or two sentences. Used in the listing, in search results and as the page description, so write it for someone who has not opened the post.', max_length=300)),
                ('hero_image_alt', models.CharField(blank=True, help_text='What the image shows. Required if an image is set.', max_length=200)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('callout', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'What the image shows, for someone who cannot see it. Leave blank only if it is purely decorative.', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 1)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog post',
                'ordering': ['-published_on'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpostpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
